# Generated by Django 2.0.4 on 2018-05-27 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('answerNo', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('answerContent', models.TextField(max_length=1000)),
                ('answerTime', models.DateField()),
                ('status', models.IntegerField(choices=[(0, '未解决'), (1, '已解决')], default=1)),
                ('isDel', models.IntegerField(choices=[(0, '未删除'), (1, '已删除')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Ask',
            fields=[
                ('askNo', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('askTopic', models.CharField(max_length=50)),
                ('askContent', models.TextField(max_length=1000)),
                ('askTime', models.DateField()),
                ('status', models.IntegerField(choices=[(0, '未解决'), (1, '已解决')], default=1)),
                ('isDel', models.IntegerField(choices=[(0, '未删除'), (1, '已删除')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('managerNo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('managerPwd', models.CharField(max_length=20)),
                ('isDel', models.IntegerField(choices=[(0, '未删除'), (1, '已删除')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('professionNo', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('isDel', models.IntegerField(choices=[(0, '未删除'), (1, '已删除')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentNo', models.IntegerField(primary_key=True, serialize=False)),
                ('studentName', models.CharField(max_length=20)),
                ('studentPwd', models.CharField(max_length=20)),
                ('studentEmail', models.EmailField(max_length=254)),
                ('studentCount', models.IntegerField(default=0)),
                ('idDel', models.IntegerField(choices=[(0, '未删除'), (1, '已删除')], default=1)),
                ('professionNos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managers.Profession')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacherNo', models.IntegerField(primary_key=True, serialize=False)),
                ('teacherName', models.CharField(max_length=20)),
                ('teacherPwd', models.CharField(max_length=20)),
                ('teacherEmail', models.EmailField(max_length=254)),
                ('teacherCount', models.IntegerField(default=0)),
                ('isDel', models.IntegerField(choices=[(0, '未删除'), (1, '已删除')], default=1)),
                ('professionNos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managers.Profession')),
            ],
        ),
        migrations.AddField(
            model_name='ask',
            name='askTypes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managers.Profession'),
        ),
        migrations.AddField(
            model_name='ask',
            name='studentNos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managers.Student'),
        ),
        migrations.AddField(
            model_name='answer',
            name='askNos',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='managers.Ask'),
        ),
        migrations.AddField(
            model_name='answer',
            name='teacherNos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managers.Teacher'),
        ),
    ]
