# Generated by Django 2.0.4 on 2018-05-29 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='isDel',
            field=models.IntegerField(choices=[(0, '未删除'), (1, '已删除')], default=0),
        ),
        migrations.AlterField(
            model_name='answer',
            name='status',
            field=models.IntegerField(choices=[(0, '未解决'), (1, '已解决')], default=0),
        ),
        migrations.AlterField(
            model_name='ask',
            name='isDel',
            field=models.IntegerField(choices=[(0, '未删除'), (1, '已删除')], default=0),
        ),
        migrations.AlterField(
            model_name='ask',
            name='status',
            field=models.IntegerField(choices=[(0, '未解决'), (1, '已解决')], default=0),
        ),
        migrations.AlterField(
            model_name='profession',
            name='isDel',
            field=models.IntegerField(choices=[(0, '未删除'), (1, '已删除')], default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='idDel',
            field=models.IntegerField(choices=[(0, '未删除'), (1, '已删除')], default=0),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='isDel',
            field=models.IntegerField(choices=[(0, '未删除'), (1, '已删除')], default=0),
        ),
    ]
